### ISSUE TITLE
Segfault on data check

### ISSUE THREAD

**Issue by sosedoff** [coinbase/rosetta-cli#209]
Reporting a fresh segfault after running a data check:

```
docker exec -it avalanche-testnet /app/rosetta-cli check:data --configuration-file=/app/rosetta-cli-conf/testnet/config.json
loaded configuration file: /app/rosetta-cli-conf/testnet/config.json
Using temporary directory /tmp/880823690
badger 2020/12/23 22:43:54 INFO: All 0 tables opened in 0s
2020/12/23 22:43:54 Loading previously seen accounts (this could take a while)...
Initialized reconciler with 0 previously seen accounts
2020/12/23 22:43:54 check:data status server running on port 9090
2020/12/23 22:43:54 Syncing 0-4965
2020/12/23 22:43:54 increasing syncer concurrency to 5 (projected new cache size: 0.176954 MB)
2020/12/23 22:43:54 increasing syncer concurrency to 6 (projected new cache size: 0.212345 MB)
2020/12/23 22:43:54 increasing syncer concurrency to 7 (projected new cache size: 0.247803 MB)
2020/12/23 22:43:54 increasing syncer concurrency to 8 (projected new cache size: 0.283203 MB)
2020/12/23 22:43:54 increasing syncer concurrency to 9 (projected new cache size: 0.318604 MB)
2020/12/23 22:43:54 increasing syncer concurrency to 10 (projected new cache size: 0.354004 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 11 (projected new cache size: 0.389404 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 12 (projected new cache size: 0.424805 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 13 (projected new cache size: 0.460205 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 14 (projected new cache size: 0.495605 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 15 (projected new cache size: 0.531006 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 16 (projected new cache size: 0.566406 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 17 (projected new cache size: 0.601807 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 18 (projected new cache size: 0.637207 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 19 (projected new cache size: 0.672607 MB)
2020/12/23 22:43:55 increasing syncer concurrency to 20 (projected new cache size: 0.708008 MB)
[MEMORY] Heap: 1507.164261MB Stack: 6.468750MB System: 1600.058769MB GCs: 5
[STATS] Blocks: 691 (Orphaned: 0) Transactions: 690 Operations: 2301 Reconciliations: 0 (Inactive: 0, Exempt: 0, Skipped: 0, Coverage: 100.000000%)
[PROGRESS] Blocks Synced: 690/4965 (Completed: 13.897281%, Rate: 69.100000/second) Time Remaining: 1m1s Reconciler Queue: 0 (Last Index Checked: 688)
[MEMORY] Heap: 1318.023674MB Stack: 11.937500MB System: 1939.935760MB GCs: 6
[STATS] Blocks: 1273 (Orphaned: 0) Transactions: 1273 Operations: 3900 Reconciliations: 1811 (Inactive: 106, Exempt: 0, Skipped: 0, Coverage: 98.360656%)
[PROGRESS] Blocks Synced: 1275/4965 (Completed: 25.679758%, Rate: 63.800000/second) Time Remaining: 57s Reconciler Queue: 5 (Last Index Checked: 1270)
[MEMORY] Heap: 1871.043312MB Stack: 11.906250MB System: 2009.857155MB GCs: 6
[STATS] Blocks: 1818 (Orphaned: 0) Transactions: 1818 Operations: 5697 Reconciliations: 4586 (Inactive: 276, Exempt: 0, Skipped: 0, Coverage: 99.497487%)
[PROGRESS] Blocks Synced: 1817/4965 (Completed: 36.596173%, Rate: 60.633333/second) Time Remaining: 51s Reconciler Queue: 0 (Last Index Checked: 1817)
[MEMORY] Heap: 1752.580231MB Stack: 12.093750MB System: 2149.488029MB GCs: 7
[STATS] Blocks: 2325 (Orphaned: 0) Transactions: 2325 Operations: 7486 Reconciliations: 6569 (Inactive: 954, Exempt: 0, Skipped: 0, Coverage: 99.604743%)
[PROGRESS] Blocks Synced: 2324/4965 (Completed: 46.807654%, Rate: 58.125000/second) Time Remaining: 45s Reconciler Queue: 0 (Last Index Checked: 2322)
[MEMORY] Heap: 1500.706741MB Stack: 9.843750MB System: 2285.247810MB GCs: 8
[STATS] Blocks: 2805 (Orphaned: 0) Transactions: 2806 Operations: 9145 Reconciliations: 8160 (Inactive: 1376, Exempt: 0, Skipped: 0, Coverage: 100.000000%)
[PROGRESS] Blocks Synced: 2817/4965 (Completed: 56.737160%, Rate: 56.360000/second) Time Remaining: 38s Reconciler Queue: 16 (Last Index Checked: 2803)
[MEMORY] Heap: 2148.121887MB Stack: 8.031250MB System: 2288.060310MB GCs: 8
[STATS] Blocks: 3219 (Orphaned: 0) Transactions: 3232 Operations: 10630 Reconciliations: 9129 (Inactive: 1376, Exempt: 0, Skipped: 0, Coverage: 97.035040%)
[PROGRESS] Blocks Synced: 3226/4965 (Completed: 64.974824%, Rate: 53.783333/second) Time Remaining: 32s Reconciler Queue: 66 (Last Index Checked: 3198)
[MEMORY] Heap: 1669.325676MB Stack: 12.875000MB System: 2354.438248MB GCs: 9
[STATS] Blocks: 3627 (Orphaned: 0) Transactions: 3646 Operations: 12115 Reconciliations: 10311 (Inactive: 1797, Exempt: 0, Skipped: 0, Coverage: 99.508600%)
[PROGRESS] Blocks Synced: 3635/4965 (Completed: 73.212487%, Rate: 51.942857/second) Time Remaining: 25s Reconciler Queue: 272 (Last Index Checked: 3507)
Reconciliation failed for 0x3c2AbF8a65B73d5bdD16103bC2d9ad19C83D62ff at 3574 computed: 50000000000AVAX live: 0AVAX
[MEMORY] Heap: 1843.663017MB Stack: 12.593750MB System: 2354.438248MB GCs: 9
2020/12/23 22:45:07 check:data status server shutting down


Error: reconciliation failure: active reconciliation error for 0x3c2AbF8a65B73d5bdD16103bC2d9ad19C83D62ff at 3574 (computed: 50000000000AVAX, live: 0AVAX)

+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation         | PASSED |
|                    | serviced all requests          |        |
+--------------------+--------------------------------+--------+
| Response Assertion | All responses are correctly    | PASSED |
|                    | formatted                      |        |
+--------------------+--------------------------------+--------+
| Block Syncing      | Blocks are connected into a    | PASSED |
|                    | single canonical chain         |        |
+--------------------+--------------------------------+--------+
| Balance Tracking   | Account balances did not go    | PASSED |
|                    | negative                       |        |
+--------------------+--------------------------------+--------+
| Reconciliation     | No balance discrepencies were  | FAILED |
|                    | found between computed and     |        |
|                    | live balances                  |        |
+--------------------+--------------------------------+--------+

+--------------------------+--------------------------------+------------+
|     CHECK:DATA STATS     |          DESCRIPTION           |   VALUE    |
+--------------------------+--------------------------------+------------+
| Blocks                   | # of blocks synced             |       3766 |
+--------------------------+--------------------------------+------------+
| Orphans                  | # of blocks orphaned           |          0 |
+--------------------------+--------------------------------+------------+
| Transactions             | # of transaction processed     |       3785 |
+--------------------------+--------------------------------+------------+
| Operations               | # of operations processed      |      12573 |
+--------------------------+--------------------------------+------------+
| Active Reconciliations   | # of reconciliations performed |       8667 |
|                          | after seeing an account in a   |            |
|                          | block                          |            |
+--------------------------+--------------------------------+------------+
| Inactive Reconciliations | # of reconciliations performed |       2239 |
|                          | on randomly selected accounts  |            |
+--------------------------+--------------------------------+------------+
| Exempt Reconciliations   | # of reconciliation failures   |          0 |
|                          | considered exempt              |            |
+--------------------------+--------------------------------+------------+
| Failed Reconciliations   | # of reconciliation failures   |          1 |
+--------------------------+--------------------------------+------------+
| Skipped Reconciliations  | # of reconciliations skipped   |          0 |
+--------------------------+--------------------------------+------------+
| Reconciliation Coverage  | % of accounts that have been   | 93.981481% |
|                          | reconciled                     |            |
+--------------------------+--------------------------------+------------+

badger 2020/12/23 22:45:07 INFO: Storing value log head: {Fid:0 Len:33 Offset:13496905}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9360df]

goroutine 10227298 [running]:
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc000500800, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:629 +0xdf
github.com/dgraph-io/badger/v2.(*DB).get(0xc000500800, 0xc072a7e8c0, 0x99, 0x99, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:664 +0x92
github.com/dgraph-io/badger/v2.(*Txn).Get(0xc072a5c5a0, 0xc072a7e820, 0x91, 0xa0, 0x9a2ab7, 0xc0000207e0, 0xc43b80)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/txn.go:471 +0xf0
github.com/coinbase/rosetta-sdk-go/storage/database.(*BadgerTransaction).Get(0xc07261fb00, 0xe62200, 0xc072652400, 0xc072a7e820, 0x91, 0xa0, 0xe00, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.6.5/storage/database/badger_database.go:453 +0x10a
github.com/coinbase/rosetta-sdk-go/storage/modules.storeUniqueKey(0xe62200, 0xc072652400, 0xe64aa0, 0xc07261fb00, 0xc072a7e820, 0x91, 0xa0, 0xc0708c58c0, 0x281, 0x281, ...)
	/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.6.5/storage/modules/utils.go:32 +0x8a
github.com/coinbase/rosetta-sdk-go/storage/modules.(*BlockStorage).storeTransaction(0xc000115c50, 0xe62200, 0xc072652400, 0xe64aa0, 0xc07261fb00, 0xc072e88ea0, 0xc072e8d350, 0xc07c793768, 0x41222b)
	/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.6.5/storage/modules/block_storage.go:970 +0x345
github.com/coinbase/rosetta-sdk-go/storage/modules.(*BlockStorage).SeeBlock.func1(0xc0720e73e0, 0xc07c793790)
	/go/pkg/mod/github.com/coinbase/rosetta-sdk-go@v0.6.5/storage/modules/block_storage.go:697 +0x67
github.com/neilotoole/errgroup.(*Group).startG.func1(0xc07261ff80)
	/go/pkg/mod/github.com/neilotoole/errgroup@v0.1.5/errgroup.go:206 +0x8e
created by github.com/neilotoole/errgroup.(*Group).startG
	/go/pkg/mod/github.com/neilotoole/errgroup@v0.1.5/errgroup.go:191 +0x5c
make: *** [check-testnet-data] Error 2
```

Not sure how to reproduce yet, but wanted to bring this issue up in here.

**Comment by patrick-ogrady** [comment]
Thanks for sharing, @sosedoff! Would you mind running `rosetta-cli version` and sharing the output?

**Comment by patrick-ogrady** [comment]
This appears to be a panic somewhere in badger 😬 ... wondering if there is some byte array we are reclaiming for reuse that we shouldn't be 🤔

**Comment by patrick-ogrady** [comment]
This appears to be the source of the panic: https://github.com/dgraph-io/badger/blob/d5a25b83fbf4f3f61ff03a9202e36f5b75544426/skl/skl.go#L84-L87

**Comment by sosedoff** [comment]
I think the cli version was 0.6.4. Config is the one you're used to test avax rosetta (per DM). i havent see any panics in 0.6.6 so maybe this issue has already been fixed.

**Comment by sosedoff** [comment]
Closing this for now since the issue seems to be fixed. Will reopen if i see it again.
